version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build: 
  commands:
   - sam build
   - export BUCKET=cc3voices
   - sam package --s3-bucket $BUCKET --output-template-file packaged-template.yml 
artifacts:
 files:
  - template.yml
  - packaged-template.yml